export const MHT_MAX_BYTES=50*1024*1024;
export class MhtError extends Error{constructor(code,message){super(message);this.name='MhtError';this.code=code}}
const enc=new TextEncoder(), latin=b=>new TextDecoder('iso-8859-1').decode(b);
const find=(a,b,s=0)=>{outer:for(let i=s;i<=a.length-b.length;i++){for(let j=0;j<b.length;j++)if(a[i+j]!==b[j])continue outer;return i}return-1};
const headerEnd=(b,s=0)=>{for(let i=s;i<b.length-1;i++){if(b[i]===13&&b[i+1]===10&&b[i+2]===13&&b[i+3]===10)return[i,4];if(b[i]===10&&b[i+1]===10)return[i,2]}return null};
const headers=t=>Object.fromEntries(t.replace(/\r?\n[ \t]+/g,' ').split(/\r?\n/).map(l=>{const i=l.indexOf(':');return i>0?[l.slice(0,i).trim().toLowerCase(),l.slice(i+1).trim()]:null}).filter(Boolean));
const param=(v,n)=>(String(v||'').match(new RegExp(`(?:^|;)\\s*${n}\\s*=\\s*(?:"([^"]+)"|([^;\\s]+))`,'i'))||[]).slice(1).find(Boolean)||'';
function decode(b,e='8bit'){e=e.toLowerCase();if(['7bit','8bit','binary',''].includes(e))return b;if(e==='quoted-printable'){const o=[];for(let i=0;i<b.length;i++){if(b[i]!==61){o.push(b[i]);continue}if(b[i+1]===13&&b[i+2]===10){i+=2;continue}if(b[i+1]===10){i++;continue}const h=String.fromCharCode(b[i+1]||0,b[i+2]||0);if(/^[\da-f]{2}$/i.test(h)){o.push(parseInt(h,16));i+=2}else o.push(61)}return new Uint8Array(o)}if(e==='base64'){const v=latin(b).replace(/\s/g,'');if(!/^[\w+/]*={0,2}$/.test(v)||v.length%4===1)throw new MhtError('INVALID_BASE64','Malformed base64 part');try{return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}catch{throw new MhtError('INVALID_BASE64','Malformed base64 part')}}throw new MhtError('UNSUPPORTED_ENCODING',`Unsupported transfer encoding: ${e}`)}
export function parseMhtBytes(input){const b=input instanceof Uint8Array?input:new Uint8Array(input||0);if(!b.length)throw new MhtError('EMPTY_FILE','MHT file is empty');if(b.length>MHT_MAX_BYTES)throw new MhtError('FILE_TOO_LARGE','MHT exceeds 50 MB');const he=headerEnd(b);if(!he)throw new MhtError('MALFORMED_MIME','MIME headers are incomplete');const root=headers(latin(b.slice(0,he[0]))),ct=root['content-type']||'';if(!/^multipart\//i.test(ct))throw new MhtError('NOT_MHT','Root is not multipart MIME');const boundary=param(ct,'boundary');if(!boundary)throw new MhtError('MALFORMED_MULTIPART','MIME boundary is missing');const marker=enc.encode(`--${boundary}`),parts=[];let cur=find(b,marker,he[0]+he[1]);if(cur<0)throw new MhtError('MALFORMED_MULTIPART','MIME boundary was not found');while(cur>=0){cur+=marker.length;if(b[cur]===45&&b[cur+1]===45)break;if(b[cur]===13&&b[cur+1]===10)cur+=2;else if(b[cur]===10)cur++;const next=find(b,marker,cur);if(next<0)throw new MhtError('MALFORMED_MULTIPART','Closing boundary is missing');let end=next;if(b[end-2]===13&&b[end-1]===10)end-=2;else if(b[end-1]===10)end--;const pe=headerEnd(b,cur);if(!pe||pe[0]>=end)throw new MhtError('MALFORMED_PART','Part headers are incomplete');const h=headers(latin(b.slice(cur,pe[0]))),type=(h['content-type']||'application/octet-stream').split(';')[0].trim().toLowerCase(),bytes=decode(b.slice(pe[0]+pe[1],end),h['content-transfer-encoding']);let value=null;if(type==='text/html'){try{value=new TextDecoder(param(h['content-type'],'charset')||'utf-8').decode(bytes)}catch{throw new MhtError('UNSUPPORTED_CHARSET',`Unsupported charset: ${param(h['content-type'],'charset')}`)}}parts.push({contentType:type,contentLocation:(h['content-location']||'').replace(/^<|>$/g,''),byteLength:bytes.length,bytes,text:value});cur=next}const html=parts.find(p=>p.contentType==='text/html'&&/^https?:/.test(p.contentLocation))||parts.find(p=>p.contentType==='text/html');if(!html)throw new MhtError('HTML_PART_MISSING','MHT contains no text/html part');return{sourceUrl:html.contentLocation||root['content-location']||null,html:html.text,resources:parts.map(({contentType,contentLocation,byteLength})=>({contentType,contentLocation,byteLength})),parts}}
export async function parseMht(file){if(!file||typeof file.arrayBuffer!=='function')throw new MhtError('INVALID_FILE','A browser File is required');if(!/\.(mht|mhtml)$/i.test(file.name||'')&&!/multipart\/related|message\/rfc822/i.test(file.type||''))throw new MhtError('NOT_MHT','Select an .mht or .mhtml file');return parseMhtBytes(await file.arrayBuffer())}
export async function sha256Hex(input){const hash=await crypto.subtle.digest('SHA-256',input instanceof Uint8Array?input:new Uint8Array(input));return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
